---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  changed_when: false
  register: current_hostname

- name: Ensure packages database is up to date
  become: yes
  apt: update_cache=yes cache_valid_time=3600

- name: Install MySQL Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Update root password for all root accounts
  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ mysql.root_password }} login_user=root login_password={{ mysql.root_password }}
  with_items:
    - "{{ current_hostname.stdout | lower }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Create databases
  mysql_db: name={{ item.database }} state=present login_user=root login_password={{ mysql.root_password }}
  when: item.database
  with_items:
    - "{{ mysql.databases }}"

- name: Import dump
  mysql_db: name={{ item.database }} state=import login_user=root login_password={{ mysql.root_password }} target=/vagrant/{{ item.dump }}
  when: item.database and item.dump
  with_items:
    - "{{ mysql.databases }}"

- name: Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent login_user=root login_password={{ mysql.root_password }}
  with_items:
    - localhost
    - "{{ current_hostname.stdout | lower }}"

- name: Create users
  mysql_user: name={{ mysql.user }} password={{ mysql.password }} priv={{ item.database }}.*:ALL state=present login_user=root login_password={{ mysql.root_password }}
  when: item.database is defined
  with_items:
    - "{{ mysql.databases }}"
